language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install --use-mirrors .
  - pip install --use-mirrors coveralls coverage
script: coverage run --source=pytool setup.py test
after_success: coveralls
